name: ncar_env1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - tensorflow
      - opencv-python
      - imutils
      - art
      - tflite-runtime